"""empty message

Revision ID: b22e1da15fb7
Revises: 41ce7a95ee7a
Create Date: 2025-06-27 19:28:00.383620

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b22e1da15fb7'
down_revision = '41ce7a95ee7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('savingGoal')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('savingGoal',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('target', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('target_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('started_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('current_saved', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('savingGoal_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('savingGoal_pkey'))
    )
    # ### end Alembic commands ###
