"""empty message

Revision ID: f6cd25a988fd
Revises: 8060399e2914
Create Date: 2025-07-27 13:20:46.297643

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6cd25a988fd'
down_revision = '8060399e2914'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expenseType', sa.String(length=255), nullable=True))
        batch_op.drop_column('ExpenseType')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ExpenseType', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.drop_column('expenseType')

    # ### end Alembic commands ###
